# Generated by Django 3.1.2 on 2020-10-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=40)),
                ('shipping', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('street', models.CharField(blank=True, max_length=40)),
                ('house', models.CharField(blank=True, max_length=40)),
                ('specific_directions', models.CharField(blank=True, max_length=40)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, choices=[('On The Way', 'On The Way'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('flavour_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flavour')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='flavour',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
