# Generated by Django 3.1.2 on 2020-11-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
